include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.mocks.dart'
    - 'lib/generated/**'
    - 'test/.test_coverage.dart'
  errors:
    invalid_annotation_target: ignore
    todo: ignore
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    flutter_style_todos: true
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_print: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    avoid_slow_async_io: true
    avoid_type_to_string: true
    avoid_web_libraries_in_flutter: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    empty_catches: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    sort_pub_dependencies: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    use_build_context_synchronously: true
    use_key_in_widget_constructors: true
